/**
 * blazie's vocabulary, as the control plane may quote it.
 *
 * GENERATED by `just onto-words` from `.monty/ontology.db`. Do not edit — the
 * database is the source, and `just check` fails when this file disagrees with
 * it.
 *
 * It exists because the MCP surface has to describe a cluster, a world and a
 * Studio to an agent, and those descriptions already exist. Retyping one makes a
 * second copy of a definition that nothing compares, which is precisely the
 * drift the ontology was built to catch.
 */

export type Word = {
  name: string
  code: string
  definition: string
  /** The one-line "what is it" test, where the word carries one. */
  test?: string
}

export const WORDS: Record<string, Word> = {
  "ask": {
    "name": "ask",
    "code": "ask",
    "definition": "Putting a question to a snapshot and being given the facts that answer it. The same question against the same snapshot gives the same facts forever, so a caller caches on the pair and never invalidates: there is no cache-coherence protocol here because there is nothing to cohere.",
    "test": "Is this a read that changes nothing and would answer the same tomorrow?"
  },
  "att": {
    "name": "attribute",
    "code": "att",
    "definition": "What a fact says about an id. An attribute is itself a defined thing with facts describing it, which is why schema and vocabulary need no words of their own.",
    "test": "Is it what is being said, rather than which thing or what the answer is? Then it is an attribute."
  },
  "blb": {
    "name": "blob",
    "code": "blb",
    "definition": "Bytes too big to be a value, standing where a value goes: an image, a video, a file, a checkout. The fact holds a reference — a key, a hash, a size — and the bytes live in object storage. Content-addressed, so the same bytes are one object and the reference is immutable in the way a snapshot is.",
    "test": "Would putting it in the log make the log carry it forever? Then it is a blob, not a value."
  },
  "clu": {
    "name": "cluster",
    "code": "clu",
    "definition": "A running blazie, reachable at an address, holding worlds. One or more nodes that agree on who owns which world — from outside, the thing you point a console or a client at; from inside, the set of nodes sharing name claims. Both are the same machines, so both are this word. You OPEN a cluster, the verb a world already uses.",
    "test": "Could you point a client at it and ask a question? Then it is a cluster. If it is one machine inside one, it is a node, which is not a word here because nothing outside this repo has to know there is more than one."
  },
  "ctl": {
    "name": "control plane",
    "code": "ctl",
    "definition": "What decides, as against what holds. It signs you in, remembers which clusters are yours, makes and unmakes the machines and the way in to them, and is the only thing that may present a credential to a cluster. It holds no worlds and answers no questions about data — asking it what is in a world is a category error, because it does not know and must not.",
    "test": "Would it still be needed if you already had every cluster you wanted, running? If no, it is control plane. If yes, it is a cluster."
  },
  "fac": {
    "name": "fact",
    "code": "fac",
    "definition": "The row, and the only row shape: an id, an attribute said about it, the answer, and the transaction that recorded it. Optionally, the formula or job that produced it. Data, schema, formulas and jobs are all facts; there is no second kind of row.",
    "test": "Can you say it as an id, something said about it, and the answer? Then it is a fact."
  },
  "fml": {
    "name": "formula",
    "code": "fml",
    "definition": "A fact declaring facts that follow from facts that already exist. A formula says what, never when. Derived answers, relations and the indexes the engine builds for itself are all formulas.",
    "test": "Does it say what a thing is rather than when to compute it? Then it is a formula."
  },
  "gen": {
    "name": "generative programming",
    "code": "gen",
    "definition": "Writing programs whose stochastic parts are constrained by verification rather than by hope. A generative program contains calls to a model; the discipline is keeping the uncertainty they introduce from accumulating — every call circumscribed by a requirement, no unverified output allowed to land, a failed check carrying its reason into the repair. Here it reaches one step further: a program's SOURCE may itself be generated, verified against examples before adoption, and stored as facts.",
    "test": "Would the output be trusted if nothing checked it? If yes it is prompting. If no, and something does check, it is generative programming."
  },
  "job": {
    "name": "job",
    "code": "job",
    "definition": "Declared work that needs the outside world: fetching, calling a hosted model, an agent taking a turn. A job runs with network, cannot be reproduced, and is the only thing a schedule can attach to.",
    "test": "Does it need something the database does not already have? Then it is a job."
  },
  "snp.name": {
    "name": "name",
    "code": "snp.name",
    "definition": "What a thing is called, as opposed to where it currently is. A ledger's name is a term its tenant chose; a snapshot's name is which ledgers at which transactions — a map of the first kind of name to a number. Both are small, serialisable, and the thing a caller actually holds, never the facts. Because a name is a plain value anyone can write by hand, every operation carrying one is authorized against it rather than trusted. Different things are called different kinds of thing, which is why this is a noun with renderings and not a value type promising one shape.",
    "test": "Is this what something is called, rather than where it is or what it holds?"
  },
  "opn": {
    "name": "open",
    "code": "opn",
    "definition": "Naming the ledgers to read and being given a snapshot of them. Opening is the only place authorization happens, because naming is what is authorized — a caller holds no rights over facts, only over the ledgers it may name.",
    "test": "Did a caller say which ledgers, and get back something it can ask?"
  },
  "ask.question": {
    "name": "question",
    "code": "ask.question",
    "definition": "What is put to a snapshot: which facts are wanted, described rather than fetched. A question is data and not code — it names ids, attributes and answers to match — so the same question travels over the wire, is stored as a fact, and caches against a name. A formula is a question somebody kept.",
    "test": "Is this a description of which facts are wanted, containing no instructions?"
  },
  "ref": {
    "name": "refinement",
    "code": "ref",
    "definition": "A change to a declaration, proposed from what runs actually did and kept with the evidence that prompted it. A refinement is a fact like everything else, so adopting one is appending and undoing one is appending a later fact rather than restoring a backup — and because the trigger is written beside the edit, whether it helped is a query over the runs that came after it. What may be refined is deliberately narrow: what a thing SAYS about itself, never what it is allowed to do.",
    "test": "Could you ask why this was changed, and whether it helped? Then it is a refinement. If it is a change nobody recorded a reason for, it is an edit."
  },
  "run": {
    "name": "run",
    "code": "run",
    "definition": "One turn-by-turn execution of the loop, and the trajectory it leaves behind. A run is an id every turn is written under — what was asked, what came back, what it cost, which tools it called, which requirements held — so it is a thing that can be resumed, forked and asked questions of rather than a log that scrolled past. Resuming one is reading its own facts; forking one is opening its snapshot at a transaction and continuing differently, and both branches stay answerable because nothing was overwritten to make the second.",
    "test": "Could you ask what it did after it finished, and carry on from where it stopped? Then it is a run. If it left nothing behind, it was a call."
  },
  "snp": {
    "name": "snapshot",
    "code": "snp",
    "definition": "One or more ledgers read at a transaction. A snapshot is what you hold and compute over — the argument to a query, never the endpoint of one.",
    "test": "Does the same question give the same answer forever? Then it is a snapshot."
  },
  "std": {
    "name": "studio",
    "code": "std",
    "definition": "A set of worlds and a caller that may name exactly those. The tenant boundary: two Studios on one cluster cannot see each other, because seeing requires naming and naming is refused at the door. It is not a machine, not an account, and not a second copy of anything — it is a grant.",
    "test": "Could two of them share a machine and still not see each other? Then it is a Studio. If isolating them needs another machine, that is a cluster and the isolation is the wrong shape."
  },
  "sym": {
    "name": "symbol",
    "code": "sym",
    "definition": "A derived stand-in for content, sitting where a fact's answer goes: a vector, a hash, a sketch, a signature. You do not read a symbol, you compare it. Always produced by a formula, never taken from outside.",
    "test": "Does it stand for content you would otherwise have to read, and is it only ever compared? Then it is a symbol."
  },
  "fac.value": {
    "name": "value",
    "code": "fac.value",
    "definition": "The third slot of a fact: what the attribute says about the id. A value is a literal, a reference to another id, or a symbol standing in for content. What an ask gives back is facts — reading one value means reading one fact's.",
    "test": "Is this the thing inside one fact, rather than the result of a read?"
  },
  "wch": {
    "name": "watch",
    "code": "wch",
    "definition": "The same question asked again as a snapshot advances. A watch is not a second mechanism beside ask; it is an ask that keeps answering, and every answer carries the snapshot it was answered at, so a caller caches it like any other.",
    "test": "Is this an ask that keeps answering, rather than a subscription of its own?"
  },
  "wor": {
    "name": "world",
    "code": "wor",
    "definition": "Where data lives, and what a chunk of Lua sees: an append-only sequence of facts, named and claimed by whoever holds it. A world is readable, forkable and deletable on its own; a tenant is one or more worlds. Nothing in one is ever rewritten, so a correction is a later fact and the earlier one still answers at the snapshot it was written into.",
    "test": "Could you claim it by name and run a chunk against it? Then it is a world."
  },
  "wrt": {
    "name": "write",
    "code": "wrt",
    "definition": "Adding facts to a ledger and being given the snapshot that includes them. Nothing is changed and nothing is removed: a correction is a later fact, and the earlier one still answers at the snapshot it was written into.",
    "test": "Does this add facts and hand back a snapshot, rather than modify one?"
  }
}
