/**
 * Render the MCP surface into a skill, from the surface itself.
 *
 * A skill telling an agent what blazie can do is documentation of an interface,
 * and hand-written documentation of an interface is the drift problem with extra
 * steps: it is correct on the day it is written and silently wrong afterwards,
 * and nothing fails when it goes wrong.
 *
 * So it is not written. `TOOLS` in `lib/control/mcp.ts` is the array the server
 * answers `tools/list` from AND dispatches `tools/call` through; this reads the
 * same array and renders it. `--check` fails when the committed file is not what
 * the array currently says, which puts the drift in `just check` rather than in
 * a reader's assumptions.
 *
 *   node --experimental-strip-types scripts/mcp-skill.mts [--check]
 */

import { readFileSync, mkdirSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

import { TOOLS } from "../web/lib/control/mcp.ts"
import { CEILING } from "../web/lib/control/remit.ts"

const HERE = dirname(fileURLToPath(import.meta.url))
const OUT = join(HERE, "..", ".claude", "skills", "blazie", "SKILL.md")

function required(tool: (typeof TOOLS)[number]): Set<string> {
  return new Set(tool.inputSchema.required ?? [])
}

function render(): string {
  const lines: string[] = []

  lines.push("---")
  lines.push("name: blazie")
  lines.push(
    "description: Work against a blazie cluster through the control plane's MCP server — run Lua against worlds, claim worlds, read how a cluster is opening. Use when the task touches a blazie backend.",
  )
  lines.push("---")
  lines.push("")
  lines.push("# blazie")
  lines.push("")
  lines.push(
    "GENERATED by `just mcp-skill` from `web/lib/control/mcp.ts`. Do not edit — the tool array is the source, and `just check` fails when this file disagrees with it.",
  )
  lines.push("")
  lines.push("## What you are talking to")
  lines.push("")
  lines.push(
    "The control plane, not a cluster. It holds every credential and performs the operations; you hold a grant and never a credential. That is deliberate: anything you read can instruct you, so your token is assumed compromised and bounded by a remit rather than trusted.",
  )
  lines.push("")
  lines.push(
    `A remit says which worlds you may name, whether you may open or remove clusters, and how many may run at once (never more than ${CEILING.most}). It expires — at most ${CEILING.days} days.`,
  )
  lines.push("")
  lines.push("## The rule that matters most")
  lines.push("")
  lines.push(
    "**Every refusal carries a repair.** A boundary here never rejects without saying how to comply, so when a tool answers with an error, the repair is the instruction — read it and follow it rather than retrying the same call or guessing.",
  )
  lines.push("")
  lines.push("## Tools")
  lines.push("")

  for (const tool of TOOLS) {
    const must = required(tool)
    lines.push(`### \`${tool.name}\` — ${tool.title}`)
    lines.push("")
    lines.push(tool.description)
    lines.push("")

    const args = Object.entries(tool.inputSchema.properties)
    if (args.length === 0) {
      lines.push("Takes nothing.")
    } else {
      lines.push("| argument | | |")
      lines.push("|---|---|---|")
      for (const [name, shape] of args) {
        const said = shape as { type?: string; description?: string; enum?: string[] }
        const kind = said.enum ? said.enum.map((one) => `\`${one}\``).join(" · ") : said.type
        lines.push(
          `| \`${name}\` | ${must.has(name) ? "required" : "optional"} | ${kind} — ${said.description ?? ""} |`,
        )
      }
    }
    lines.push("")
  }

  return `${lines.join("\n")}\n`
}

const wanted = render()

if (process.argv.includes("--check")) {
  let held = ""
  try {
    held = readFileSync(OUT, "utf8")
  } catch {
    held = ""
  }

  if (held !== wanted) {
    console.error(
      `.claude/skills/blazie/SKILL.md is not what the tool array says.\nRun \`just mcp-skill\` and commit the result.`,
    )
    process.exit(1)
  }

  console.log(`skill: ${TOOLS.length} tools in step with the surface`)
} else {
  mkdirSync(dirname(OUT), { recursive: true })
  writeFileSync(OUT, wanted)
  console.log(`wrote .claude/skills/blazie/SKILL.md — ${TOOLS.length} tools`)
}
