#!/usr/bin/env python3
"""
Render blazie's vocabulary into TypeScript, so the control plane can quote it.

The MCP surface describes clusters, worlds and Studios to an agent, and those
words already have definitions that were argued over and written down once. An
agent-facing description retyped by hand is a second copy of a definition, which
is the exact failure the ontology exists to prevent — it drifts, and the drift is
invisible because nothing compares the two.

So nothing is retyped. This reads `.monty/ontology.db` and writes a module the
worker imports; `just onto-words --check` fails when the checked-in file is not
what the database currently says, which makes the drift a red build rather than
a discovery.

A Worker cannot open sqlite, which is why this is a build step and not a query.
"""

import argparse
import json
import pathlib
import sqlite3
import sys

HERE = pathlib.Path(__file__).resolve().parent.parent
DB = HERE / ".monty" / "ontology.db"
OUT = HERE / "web" / "lib" / "control" / "words.ts"

HEAD = '''/**
 * blazie's vocabulary, as the control plane may quote it.
 *
 * GENERATED by `just onto-words` from `.monty/ontology.db`. Do not edit — the
 * database is the source, and `just check` fails when this file disagrees with
 * it.
 *
 * It exists because the MCP surface has to describe a cluster, a world and a
 * Studio to an agent, and those descriptions already exist. Retyping one makes a
 * second copy of a definition that nothing compares, which is precisely the
 * drift the ontology was built to catch.
 */

export type Word = {
  name: string
  code: string
  definition: string
  /** The one-line "what is it" test, where the word carries one. */
  test?: string
}

export const WORDS: Record<string, Word> = '''


def read() -> dict:
    if not DB.exists():
        sys.exit(f"no ontology at {DB}")

    db = sqlite3.connect(f"file:{DB}?mode=ro", uri=True)
    rows = db.execute(
        "select name, code, definition, test from word where code is not null order by name"
    ).fetchall()
    db.close()

    words = {}
    for name, code, definition, test in rows:
        one = {"name": name, "code": code, "definition": " ".join(definition.split())}
        if test:
            one["test"] = " ".join(test.split())
        words[code] = one

    return words


def render(words: dict) -> str:
    return HEAD + json.dumps(words, indent=2, ensure_ascii=False) + "\n"


def main() -> None:
    ask = argparse.ArgumentParser()
    ask.add_argument("--check", action="store_true", help="fail if the file is stale")
    said = ask.parse_args()

    wanted = render(read())

    if said.check:
        held = OUT.read_text() if OUT.exists() else ""
        if held != wanted:
            sys.exit(
                f"{OUT.relative_to(HERE)} is not what the ontology says.\n"
                "Run `just onto-words` and commit the result."
            )
        print(f"words: {len(read())} in step with the ontology")
        return

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(wanted)
    print(f"wrote {OUT.relative_to(HERE)} — {len(read())} words")


if __name__ == "__main__":
    main()
